name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Super-Linter
      uses: docker://github/super-linter:latest
      env:
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /client/
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
        FILTER_REGEX_INCLUDE: .*src/.*
        FILTER_REGEX_EXCLUDE: .*test/.*
        VALIDATE_HTML: false
        VALIDATE_CSS: false
        VALIDATE_TERRAFORM_TERRASCAN: false
        VALIDATE_JSON: false
        VALIDATE_KUBERNETES_KUBEVAL: false
        VALIDATE_KOTLIN: false
        VALIDATE_LATEX: false
        VALIDATE_LUA: false
        VALIDATE_MARKDOWN: false
        VALIDATE_OPENAPI: false
        VALIDATE_PERL: false
        VALIDATE_PHP: false
        VALIDATE_PHP_BUILTIN: false
        VALIDATE_PHP_PHPCS: false
        VALIDATE_PHP_PHPSTAN: false